### ISSUE TITLE
Support for gaussian lensing

### ISSUE THREAD

**Issue by damonge** [bthorne93/PySM#1]
Since Taylens takes a bit to run, people focusing on B-modes may want to generate CMB realizations using only a Gaussian realization of the lensed power spectra (this is my case for instance). This option should be very easy to add.

**Comment by damonge** [comment]
Related to this, it may be a good idea to add support for partially delensed simulations. This may be as easy as multiplying the lensing potential power spectrum by a delensing factor...

**Comment by jodunkley** [comment]
yes, good idea. and yes I think it is that easy.
